### ISSUE TITLE
Undoing a response in reviews after having used the search automatically refocuses the search bar instead of the answer box

### ISSUE THREAD

**Issue by slice** [Lemmmy/KanjiSchool#3]
If you type something into the search box during reviews and later undo, then the search box is automatically focused instead of the answer box.

https://user-images.githubusercontent.com/4206232/172938861-c929cb67-4c51-4693-a95d-22ccf83f1d2d.mov

KanjiSchool ver.: `v1.2.2-1-gfc49d38`

**Comment by Lemmmy** [comment]
Hey! Thanks for the report, and sorry for getting to this so late. I am having trouble reproducing this issue on Chrome 102, Chrome 103, Firefox 100 and Firefox 101 (all on Windows). I can try to implement a possible fix anyway - would you be able to share some more details on your environment? Operating system, browser + version, etc.

**Comment by slice** [comment]
@Lemmmy Sorry, I forgot to mention this but the issue only seems to occur if you use the keyboard shortcut (⌘Z or CTRL-Z).

**Comment by slice** [comment]
System information:

Google Chrome 102.0.5005.115 (Official Build) (arm64)
macOS 12.4 (21F79)

Reproduction steps:

1. Begin reviews.
2. Focus the search field with the mouse and type something.
3. Move focus to the response field and give an incorrect answer.
4. Press CTRL-Z (or ⌘Z).
5. The search field is unexpectedly focused instead of the response field.

**Comment by Lemmmy** [comment]
That makes much more sense, thanks for the detailed steps! The issue was indeed with Ctrl+Z specifically. Let me know if you still have any issues with it on v1.2.5!

**Comment by slice** [comment]
Awesome, thanks! 💕
