### ISSUE TITLE
[Feature Request] Allow disabling of the 'undo' capability.

### ISSUE THREAD

**Issue by AbstractUmbra** [Lemmmy/KanjiSchool#5]
I find myself overusing the undo capability when I get a review incorrect, which I feel doesn't help me recall as well as having to redo an incorrect card.

Having the ability to disable this feature (within the settings perhaps?) would be wonderful for me, as I feel I am 'cheating' by using this feature.

(I have no willpower to not use it, heh)

**Comment by Lemmmy** [comment]
Sounds like a good idea, I remember considering it for myself when I had the same problem! Will take a look at implementing this.
